import { Navbar } from "@/components/Navbar";
import "./globals.css";
import WalletProvider from "./provider/WalletProvider";

export const metadata = {
  title: "BarterX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <Navbar />
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
